export function createCrudConfigs({
  getShelters,
  getPets,
  getApplicants,
  getAdoptionRecords,
  getFollowUps,
  getMedicalRecords,
  getVaccinations,
  getVolunteers,
  getCareAssignments,
  todayIso,
  housingTypeOptions,
  petStatusOptions,
  petOptions,
  careVolunteerOptions,
}) {
  return {
    'shelters': {
      label: 'Shelter',
      endpoint: '/api/shelters',
      idField: 'shelterId',
      data: getShelters,
      fields: [
        {name:'name', label:'Name', required:true},
        {name:'address', label:'Address'},
        {name:'phone', label:'Phone'},
        {name:'capacity', label:'Capacity', type:'number', required:true},
      ],
    },
    'pets': {
      label: 'Pet',
      endpoint: '/api/pets',
      idField: 'petId',
      data: getPets,
      fields: [
        {name:'shelterId', label:'Shelter', type:'select', required:true, options: () => getShelters().map(s => ({value:s.shelterId, label:`${s.id} - ${s.name}`}))},
        {name:'name', label:'Name', required:true},
        {name:'species', label:'Species', type:'select', required:true, options: () => ['Dog','Cat','Rabbit','Bird'].map(v => ({value:v, label:v}))},
        {name:'breed', label:'Breed'},
        {name:'sex', label:'Sex', type:'select', options: () => ['Male','Female','Unknown'].map(v => ({value:v, label:v}))},
        {name:'color', label:'Color'},
        {name:'birth', label:'Estimated birth date', type:'date'},
        {name:'intake', label:'Intake date', type:'date', required:true, defaultValue: todayIso},
        {name:'status', label:'Status', type:'select', required:true, options: petStatusOptions},
        {name:'sterilized', label:'Sterilized', type:'bool'},
        {name:'special', label:'Special needs', type:'textarea', wide:true},
      ],
    },
    'applicants': {
      label: 'Applicant',
      endpoint: '/api/applicants',
      idField: 'applicantId',
      data: getApplicants,
      fields: [
        {name:'name', label:'Full name', required:true},
        {name:'phone', label:'Phone'},
        {name:'email', label:'Email', type:'email'},
        {name:'address', label:'Address', type:'textarea', wide:true},
        {name:'housingType', label:'Housing type', type:'select', options: housingTypeOptions},
        {name:'hasPetExperience', label:'Has pet experience', type:'bool'},
        {name:'createdAt', label:'Created at', type:'date', defaultValue: todayIso},
      ],
    },
    'medical-records': {
      label: 'Medical record',
      endpoint: '/api/medical-records',
      idField: 'recordId',
      data: getMedicalRecords,
      fields: [
        {name:'petId', label:'Pet', type:'select', required:true, options: petOptions},
        {name:'date', label:'Visit date', type:'date', required:true, defaultValue: todayIso},
        {name:'type', label:'Record type', type:'select', options: () => ['Check-up','Surgery','Injury','Dental','Treatment'].map(v => ({value:v, label:v}))},
        {name:'vet', label:'Vet name'},
        {name:'diagnosis', label:'Diagnosis', type:'textarea', wide:true},
        {name:'treatment', label:'Treatment', type:'textarea', wide:true},
        {name:'notes', label:'Notes', type:'textarea', wide:true},
      ],
    },
    'vaccinations': {
      label: 'Vaccination',
      endpoint: '/api/vaccinations',
      idField: 'vaccinationId',
      data: getVaccinations,
      fields: [
        {name:'petId', label:'Pet', type:'select', required:true, options: petOptions},
        {name:'vaccine', label:'Vaccine name', required:true},
        {name:'doseNo', label:'Dose no.', type:'number'},
        {name:'vaccinationDate', label:'Vaccination date', type:'date', required:true, defaultValue: todayIso},
        {name:'dueDate', label:'Next due date', type:'date'},
        {name:'vet', label:'Vet name'},
        {name:'notes', label:'Notes', type:'textarea', wide:true},
      ],
    },
    'volunteers': {
      label: 'Volunteer',
      endpoint: '/api/volunteers',
      idField: 'volunteerId',
      data: getVolunteers,
      fields: [
        {name:'shelterId', label:'Shelter', type:'select', required:true, options: () => getShelters().map(s => ({value:s.shelterId, label:`${s.id} - ${s.name}`}))},
        {name:'name', label:'Full name', required:true},
        {name:'phone', label:'Phone'},
        {name:'email', label:'Email', type:'email'},
        {name:'joined', label:'Join date', type:'date', defaultValue: todayIso},
        {name:'availability', label:'Availability note', type:'textarea', wide:true},
      ],
    },
    'care-assignments': {
      label: 'Care assignment',
      endpoint: '/api/care-assignments',
      idField: 'assignmentId',
      data: getCareAssignments,
      fields: [
        {name:'volunteerId', label:'Volunteer', type:'select', required:true, options: careVolunteerOptions},
        {name:'petId', label:'Pet', type:'select', required:true, options: petOptions},
        {name:'date', label:'Assignment date', type:'date', required:true, defaultValue: todayIso},
        {name:'shift', label:'Shift', type:'select', required:true, options: () => ['Morning','Afternoon','Evening'].map(v => ({value:v, label:v}))},
        {name:'task', label:'Task type', type:'select', required:true, options: () => ['Feeding','Cleaning','Walking','Grooming','Socializing','Medical support'].map(v => ({value:v, label:v}))},
        {name:'status', label:'Status', type:'select', required:true, options: () => ['Scheduled','Completed','Cancelled'].map(v => ({value:v, label:v}))},
        {name:'notes', label:'Notes', type:'textarea', wide:true},
      ],
    },
    'follow-ups': {
      label: 'Follow-up',
      endpoint: '/api/follow-ups',
      idField: 'followupId',
      data: getFollowUps,
      fields: [
        {name:'adoptionId', label:'Adoption record', type:'select', required:true, options: () => getAdoptionRecords().map(r => ({value:r.adoptionId, label:`${r.id} - ${r.pet} / ${r.applicant}`}))},
        {name:'followupDate', label:'Follow-up date', type:'date', required:true, defaultValue: todayIso},
        {name:'followupType', label:'Follow-up type', type:'select', required:true, options: () => ['Phone Check','Home Visit','Vet Check'].map(v => ({value:v, label:v}))},
        {name:'petCondition', label:'Pet condition'},
        {name:'adopterFeedback', label:'Adopter feedback', type:'textarea', wide:true},
        {name:'resultStatus', label:'Result status', type:'select', required:true, options: () => ['Excellent','Good','Satisfactory','Needs Improvement'].map(v => ({value:v, label:v}))},
        {name:'staffNote', label:'Staff note', type:'textarea', wide:true},
      ],
    },
  };
}
